### ISSUE TITLE
Find a better way to indicate an active session

### ISSUE THREAD

**Issue by codefoster** [regatta-app/ui#17]
the active|idle text indicator is obviously not elegant
perhaps animate the viewport with a flash, pulse it, or surround it with green?

**Comment by codefoster** [comment]
I talked with Rachel Weil about this and she had the idea of adding a bar on the top of the content box that is green when you're in an active rowing session. It could be red or yellow otherwise. And we discussed having a count down appear after you hit start. Ideas?

**Comment by timmyreilly** [comment]
That sounds cool to me! I'll take a crack at it this afternoon.

**Comment by hxlnt** [comment]
@timmyreilly walked me through the codebase yesterday--thanks!--and I've pulled down his branch to try my hand at implementing (a) a large 3-2-1 countdown timer via JQuery/CSS animation and (b) modifying my session status bar to use the Material 2 visual language and to respond to the simulated device stream.
