### ISSUE TITLE
Don't allow a session to start without rowers

### ISSUE THREAD

**Issue by codefoster** [regatta-app/ui#18]
If no rowers have checked in, then gray out the session start button.
If rowers send data, their names will appear in the rower list, but none of the values should change (it already works that way).
Also, consider whether rowers are allowed to enter a session that's already started.

**Comment by codefoster** [comment]
I'm also going to combine the START and END buttons into one in this issue

**Comment by codefoster** [comment]
done... issued PR24

**Comment by timmyreilly** [comment]
PR #24 closes issue
