### ISSUE TITLE
Determine behavior at end of session

### ISSUE THREAD

**Issue by codefoster** [regatta-app/ui#20]
When a session begins, we will default it to 150m for now (we'll have to create a UI for picking that eventually). That value should be sent in the body of the POST to /api/session/start and then the API should pass it along in the `sessionstart` message.
When a rower reaches the end, we must determine what will happen. @bzh0u let us know if you have any input on this.

**Comment by bzh0u** [comment]
Have the line showing the rower and corresponding stats turn green and bold, and stop updating the stats for that rower.

**Comment by codefoster** [comment]
Thank, @bzh0u. We'll give this a shot.

**Comment by codefoster** [comment]
PR #31 has been created to work toward this feature
